<?php
session_start();
if(!empty($_SESSION['paymentdetails']))
{
    $name=$_SESSION['paymentdetails']['name'];
    $mobile=$_SESSION['paymentdetails']['mobile'];
    $Email=$_SESSION['paymentdetails']['email'];
    $Referance=$_SESSION['paymentdetails']['ref_id'];
    $Amount=$_SESSION['paymentdetails']['amount'];
    $api_key="rzp_test_cRcU37B6W4ucEd"; 
?>
<form action="Paymentsuccess.php" method="POST">
<script
    src="https://checkout.razorpay.com/v1/checkout.js"
    data-key="<?php echo $api_key; ?>" // Enter the Test API Key ID generated from Dashboard → Settings → API Keys
    data-amount="<?php echo $Amount *100 ; ?>" // Amount is in currency subunits. Hence, 29935 refers to 29935 paise or ₹299.35.
    data-currency="INR"// You can accept international payments by changing the currency code. Contact our Support Team to enable International for your account
    data-id="<?php echo uniqid('HT'); ?>"// Replace with the order_id generated by you in the backend.
    data-buttontext="Rasid Enterprice"
    data-name="Rasid Enterprice"
    data-description="Rasid Enterprice"
    data-image="https://as2.ftcdn.net/v2/jpg/03/79/16/01/1000_F_379160151_DzuFHxITrOZwVFqSYSHnloFfEKcx7phA.jpg"
    data-prefill.name="<?php echo $name; ?>"
    data-prefill.email="<?php echo $Email; ?>"
    data-prefill.contact="<?php echo $mobile; ?>"
    data-prefill.ref="<?php echo $Referance; ?>"
    data-theme.color="#F37254"
></script>
<input type="hidden" custom="Hidden Element" name="hidden">
</form>

<script src="https://code.jquery.com/jquery-3.6.1.min.js" integrity="sha256-o88AwQnZB+VDvE9tvIXrMQaPlFFSUTR+nldQm1LuPXQ=" crossorigin="anonymous"></script>
<script>
    $('.razorpay-payment-button').hide();

 $('.razorpay-payment-button').click();
</script>
<?php
    }
    else
    {
        echo "<script>window.location='Appoinment.php?type=add'</script>";

    }

?>